# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-07-29 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1_name', models.CharField(max_length=50)),
                ('player_2_name', models.CharField(max_length=50)),
            ],
        ),
    ]
